export const personalProjects = [
    {
        id: 'beer-run-jpn',
        title: 'Beer Run',
        description: 'A live drink-tracking app I originally built for a trip to Japan, with a shared leaderboard, map, and mobile-first interface. It\'s now deployed and used by people around the world.',
        repoName: 'Matei9721/beer-run-jpn',
        githubUrl: 'https://github.com/Matei9721/beer-run-jpn',
        githubLabel: 'View Beer Run source on GitHub',
        liveUrl: 'https://beerrun.ddns.net',
        liveLabel: 'Open Beer Run live',
        logo: 'beer-run-wordmark.svg',
        tags: ['FastAPI', 'SQLite', 'Leaflet'],
        featured: true,
    },
    {
        id: 'ai-search-engine',
        title: 'AI Search Engine',
        description: 'A learning project for an agent-driven retrieval-augmented generation system that uses web search to answer questions with cited sources.',
        repoName: 'Matei9721/ai-search-engine',
        githubUrl: 'https://github.com/Matei9721/ai-search-engine',
        githubLabel: 'View AI Search Engine on GitHub',
        tags: ['Python', 'LangGraph', 'SearXNG'],
    },
    {
        id: 'portfolio-website',
        title: 'Portfolio website',
        description: 'My personal portfolio website for presenting my work, experience, projects, capabilities, and personality.',
        repoName: 'Matei9721/portfolio-website',
        githubUrl: 'https://github.com/Matei9721/portfolio-website',
        githubLabel: 'View Portfolio website on GitHub',
        tags: ['React', 'Vite', 'GitHub Pages'],
    },
    {
        id: 'project-idlab',
        title: 'Project IDLab',
        description: 'A smart calendar application built with IDLab and imec to demonstrate personal data ownership using linked data and Solid pods.',
        repoName: 'osoc22/project-idlab',
        githubUrl: 'https://github.com/osoc22/project-idlab',
        githubLabel: 'View Project IDLab on GitHub',
        tags: ['Svelte', 'TypeScript', 'Solid pods'],
    },
    {
        id: 'ashfall-dnd',
        title: 'Ashfall DM control room',
        description: 'I am a bad D&D DM, so I made a small control room to help me run my own campaign at the table.',
        repoName: 'Matei9721/ashfall-dnd',
        githubUrl: 'https://github.com/Matei9721/ashfall-dnd',
        githubLabel: 'View Ashfall DM control room on GitHub',
        tags: ['HTML', 'CSS', 'JavaScript'],
    },
];
