export const personalProjects = [
    {
        id: 'beer-run-jpn',
        title: 'BeerRunJPN',
        description: 'A drink tracker I made for a trip to Japan. It runs on a Raspberry Pi and has a shared leaderboard, a map, and a mobile-first interface.',
        repoName: 'Matei9721/beer-run-jpn',
        githubUrl: 'https://github.com/Matei9721/beer-run-jpn',
        githubLabel: 'View BeerRunJPN on GitHub',
        tags: ['FastAPI', 'SQLite', 'Leaflet'],
    },
    {
        id: 'cs-tracker',
        title: 'Romanian CS Forces',
        description: 'A Counter-Strike 2 dashboard for three Romanian friends. It reads our Leetify history, calculates the trio’s record, and includes a shared map vote.',
        repoName: 'Matei9721/cs-tracker',
        githubUrl: 'https://github.com/Matei9721/cs-tracker',
        githubLabel: 'View Romanian CS Forces on GitHub',
        tags: ['JavaScript', 'Leetify API', 'Supabase'],
    },
    {
        id: 'ashfall-dnd',
        title: 'Ashfall DM control room',
        description: 'I am a bad D&D DM, so I made a small control room to help me run my own campaign at the table.',
        repoName: 'Matei9721/ashfall-dnd',
        githubUrl: 'https://github.com/Matei9721/ashfall-dnd',
        githubLabel: 'View Ashfall DM control room on GitHub',
        tags: ['HTML', 'CSS', 'JavaScript'],
    },
    {
        id: 'anime-recommender',
        title: 'Anime recommender',
        description: 'I like watching anime. I do machine learning for work. Combining the two seemed like a fun learning project.',
        repoName: 'Matei9721/anime-recommender',
        githubUrl: 'https://github.com/Matei9721/anime-recommender',
        githubLabel: 'View Anime recommender on GitHub',
        tags: ['Anime', 'Recommendations', 'Learning project'],
    },
];
